### PR TITLE
Jenna etl branch

### PR DESCRIPTION
**Pull request by philipstubbs13**

### CODE REVIEW

**Comment by philipstubbs13** [comment]
I don't think Postgres/SQL likes NaN values.  I would convert NaN to None type.

I think to do a global find and replace, do something like this (double check my code first before implementing):

`nineteen_survey_df = nineteen_survey_df.replace({np.nan: None})

nineteen_survey_df
`

Do the same for empty string columns:

`
nineteen_survey_df = nineteen_survey_df.replace({"": None})

nineteen_survey_df
`

**Comment by philipstubbs13** [comment]
@abbylemon is doing this i believe?
Change True/False to 1/0.
0 being False, 1 being True

`
nineteen_survey_df["is_tech_company"] = nineteen_survey_df["is_tech_company"].replace({
    True: 1,
    False: 0
})

nineteen_survey_df["is_tech_company"].value_counts()
`

**Comment by philipstubbs13** [comment]
Change column name employer_provides_mental_health to employer_provides_mental_health_benefits

**Comment by jstowe026** [comment]
I have made those edits and pushed the most recent version

**Pull request merged**
